services:
  jse-avocats-bdd:
    container_name: jse-avocats-bdd
    image: mariadb:11.7.2
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bddwp
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
      start_period: 15s
      interval: 10s
      timeout: 10s
      retries: 5

  jse-avocats-wp:
    container_name: jse-avocats-wp
    image: ghcr.io/openclassrooms-student-center/jse-avocats:2-0-0
    ports:
      - 8081:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      WORDPRESS_DB_HOST: jse-avocats-bdd
      WORDPRESS_DB_NAME: bddwp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    depends_on:
      jse-avocats-bdd:
        condition: service_healthy
    
volumes:
  db_data:
